import type { ChromeCopy } from "@/content/en/chrome";

export const heChrome: ChromeCopy = {
  nav: {
    home: "בית",
    solutions: "פתרונות",
    freelancers: "פרילנסרים",
    freelancersDescription: "הבליטו את עצמכם ואספו לידים בדרכים",
    agencies: "סוכנויות",
    agenciesDescription: "כרטיסים נעולים למותג לכל חבר צוות",
    learn: "למידה",
    blog: "בלוג",
    blogDescription: "טיפים, מדריכים ועדכוני מוצר",
    successStories: "סיפורי הצלחה",
    successStoriesDescription: "איך אנשי מקצוע צומחים עם OneTap",
    faq: "שאלות נפוצות",
    faqDescription: "תשובות לשאלות נפוצות",
    pricing: "מחירים",
    signIn: "התחברות",
    getYourCard: "קבלו כרטיס",
    openMenu: "פתחו תפריט",
    closeMenu: "סגרו תפריט",
  },
  footer: {
    product: "מוצר",
    company: "חברה",
    resources: "משאבים",
    home: "בית",
    freelancers: "פרילנסרים",
    agencies: "סוכנויות",
    pricing: "מחירים",
    faq: "שאלות נפוצות",
    blog: "בלוג",
    helpCenter: "מרכז עזרה",
    terms: "תנאים",
    privacy: "פרטיות",
    cookieSettings: "הגדרות עוגיות",
    rightsReserved: "כל הזכויות שמורות.",
  },
  cookie: {
    title: "עוגיות שיווק",
    body: "אנחנו משתמשים ב-Meta Pixel כדי למדוד פרסומות בפייסבוק ובאינסטגרם אחרי המעבר ל-OneTap. אשרו כדי לאפשר זאת. עוגיות חיוניות לאתר אינן מושפעות.",
    reject: "דחייה",
    accept: "אישור",
  },
  notFound: {
    message: "העמוד הזה לא קיים — אבל החיבור הגדול הבא שלכם במרחק הקשה אחת.",
    backHome: "חזרה לדף הבית",
  },
  slugClaim: {
    submitLabel: "קבלו כרטיס",
    placeholder: "your-name",
    ariaLabelSuffix: "השם שלכם אחרי",
    asciiHint: "השתמשו באותיות באנגלית לקישור הציבורי (a-z, 0-9 ומקפים).",
  },
  hero: {
    title: "כרטיס ביקור דיגיטלי ב",
    titleAccent: "הקשה אחת.",
    titleRest: "הופיעו בכל מקום.",
    seeHowItWorks: "ראו איך זה עובד",
  },
  metadata: {
    siteTitle: "OneTap-Card | הזהות המקצועית שלכם, בהקשה אחת",
    siteDescription: "פלטפורמת כרטיסי ביקור דיגיטליים פרימיום, מבוססת ווב.",
    homeTitle: "OneTap-Card | הזהות המקצועית שלכם, בהקשה אחת",
    pricingTitle: "מחירים | OneTap-Card",
    pricingDescription: "תמחור פשוט ושקוף ליחידים ולצוותים.",
    pricingHeroTitle: "פשוט ו",
    pricingHeroAccent: "שקוף.",
    pricingHeroLead: "בין אם אתם פרילנסרים או צוות ארגוני — יש לנו תוכנית שגדלה איתכם.",
    faqTitle: "שאלות נפוצות | OneTap-Card",
    faqDescription: "תשובות לשאלות נפוצות על כרטיסי ביקור דיגיטליים של OneTap, פיצ'רים וחיוב.",
    faqHeroTitle: "יש",
    faqHeroAccent: "שאלות?",
    faqHeroLead: "כל מה שצריך לדעת על כרטיסי ביקור דיגיטליים של OneTap.",
    blogTitle: "בלוג | OneTap-Card",
    blogDescription: "טיפים לנטוורקינג, סיפורי הצלחה ועדכוני מוצר מצוות OneTap.",
    blogHeroTitle: "הבלוג של",
    blogHeroAccent: "OneTap",
    blogHeroLead: "שיטות עבודה, סיפורי הצלחה, מדריכים וחדשות לאנשי מקצוע מודרניים.",
    freelancersTitle: "כרטיסי ביקור דיגיטליים לפרילנסרים ויוצרים | OneTap-Card",
    freelancersDescription:
      "צרו כרטיס ביקור דיגיטלי ממותג תוך 60 שניות. שתפו פורטפוליו, קישורים ופרטי קשר בהקשה אחת דרך NFC או QR.",
    agenciesTitle: "כרטיסי ביקור דיגיטליים לסוכנויות וצוותים | OneTap-Card",
    agenciesDescription:
      "מיתוג אחיד ושליטה מרכזית לארגון. נהלו כרטיסי צוות, נעלו תבניות מותג, עקבו אחרי לידים וייצאו נתונים מלוח בקרה אחד.",
    postNotFound: "הפוסט לא נמצא",
  },
  blog: {
    backToBlog: "חזרה לבלוג",
    shareLabel: "שתפו את המאמר",
    minRead: "דק׳ קריאה",
    searchPlaceholder: "חיפוש פוסטים…",
    allCategories: "הכל",
    emptySearchAndCategory: "אין פוסטים שמתאימים לחיפוש או לקטגוריה.",
    emptySearch: "אין פוסטים שמתאימים לחיפוש.",
    emptyCategory: "אין פוסטים בקטגוריה זו.",
    empty: "אין פוסטים זמינים.",
  },
  faqPage: {
    searchPlaceholder: "חיפוש בשאלות נפוצות…",
    allCategories: "הכל",
    emptyFiltered: "אין שאלות שמתאימות לחיפוש או לקטגוריה.",
    empty: "אין שאלות זמינות.",
    comparePlans: "השוואת תוכניות",
    billingFaqOnPricing: "שאלות חיוב בעמוד המחירים",
  },
  language: {
    switchTo: "שפה",
  },
  search: {
    defaultPlaceholder: "חיפוש…",
  },
  pricingFaq: {
    title: "שאלות",
    accent: "חיוב",
  },
  cta: {
    getCardFree: "קבלו כרטיס בחינם",
  },
  process: {
    defaultCtaLabel: "קבלו כרטיס בחינם",
  },
};
